name: CI

on:
  pull_request:
  push:
    branches: [main]
    tags: [v*.*.*]

jobs:
  build:
    name: Test & Build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.13"]  # Changed from 3.11 to 3.13 as major version
        include:
          - os: ubuntu-latest
            python-version: "3.8"
          - os: ubuntu-latest
            python-version: "3.9"
          - os: ubuntu-latest
            python-version: "3.10"
          - os: ubuntu-latest
            python-version: "3.11"
          - os: ubuntu-latest
            python-version: "3.12"
          # 3.7 removed because it is no longer supported
    env:
      OS: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch all history for setuptools_scm to be able to read tags

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install python dependencies
        run: pip install .[dev,build]

      - name: Run tests
        shell: bash
        run: |
          # Set up git user for git command to work with tests
          git config --global user.name "tests"
          git config --global user.email "tests@example.com"
          pytest -v --cov=autobuild --cov-report=xml tests/

      - name: Build python package
        run: python -m build

      - name: Upload coverage
        uses: codecov/codecov-action@v5
        if: matrix.os == 'ubuntu-latest'
        with:
          env_vars: OS

      - uses: actions/upload-artifact@v4
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.11'
        with:
          name: dist
          path: dist

  publish:
    name: Publish to PyPI
    needs: build
    runs-on: [ubuntu-latest]
    permissions:
      id-token: write
    if: github.event_name != 'pull_request'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Test Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        if: startsWith(github.event.ref, 'refs/tags/v')
