name: CI

on:
  pull_request:
  push:
    branches: [main]
    tags: [v*.*.*]

jobs:
  build:
    name: Test & Build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04, windows-2022]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    runs-on: ${{ matrix.os }}
    env:
      OS: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev,build]

      - name: Lint & Format
        run: |
          pip install ruff
          ruff check --output-format=github .
          ruff format --check .

      - name: Run tests
        run: |
          git config --global user.name "tests"
          git config --global user.email "tests@example.com"
          pytest -v --cov=autobuild --cov-report=xml tests/

      - name: Build package
        run: python -m build

      - name: Upload coverage
        uses: codecov/codecov-action@v5
        if: matrix.os == 'ubuntu-22.04'
        with:
          env_vars: OS

      - uses: actions/upload-artifact@v4
        if: matrix.os == 'ubuntu-22.04' && matrix.python-version == '3.13'
        with:
          name: dist
          path: dist
