name: CI

on:
  pull_request:
  push:
    branches: [main]
    tags: [v*.*.*]

jobs:
  build:
    name: Test & Build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04, windows-2022]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    env:
      OS: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install python dependencies
        run: pip install .[dev,build]

      - name: Run tests
        shell: bash
        run: |
          git config --global user.name "tests"
          git config --global user.email "tests@example.com"
          pytest -v --cov=autobuild --cov-report=xml tests/

      - name: Build python package
        run: python -m build

      - name: Upload coverage
        uses: codecov/codecov-action@v5
        if: matrix.os == 'ubuntu-22.04'
        with:
          env_vars: OS

      - uses: actions/upload-artifact@v4
        if: matrix.os == 'ubuntu-22.04' && matrix.python-version == '3.13'
        with:
          name: dist
          path: dist

  publish:
    name: Publish to PyPI
    needs: build
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
    if: github.event_name != 'pull_request'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Test Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        if: startsWith(github.event.ref, 'refs/tags/v')
